language: node_js
node_js:
  - "4"
  - "5"
  - "6"
addons:
  firefox: "39.0"
install:
  - npm install -g http-server
  - npm install
script:
  - npm run build
  - npm run test
branches:
  only:
    - truss-core-refactor
